version: '3.8'

services:
  nextcloud:
    image: nextcloud:stable@sha256:bb3672cdb9dfccb2159da88826981a8d749f5d4cd9a2816c1f32d93e08f541eb
    hostname: nextcloud
    container_name: nextcloud__nextcloud
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: mariadb
      OVERWRITEPROTOCOL: "https"

    volumes:
      - type: volume
        source: nextcloud_data
        target: /var/www/html

    deploy:
      resources:
        limits:
          memory: 1024m

    networks:
      default:
      outband:

  mariadb:
    image: mariadb:12.3.2@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
    hostname: mariadb
    container_name: nextcloud__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      default:

  nginx:
    image: nginx:1.31.2@sha256:ec4ed8b5299e5e90694af7750eb6dffd2627317d30544d056b0371f8082f7bce
    hostname: nginx
    container_name: nextcloud__nginx
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    networks:
      default:

  cloudflared:
    image: cloudflare/cloudflared:2026.6.1-amd64@sha256:95de18ccf4e51bd9d2ba28fe7218e423adc6a88fad1aee910eb67c306b7af2c4
    hostname: cloudflared
    container_name: nextcloud__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - nextcloud__cloudflared

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: nextcloud__default
    internal: true

  outband:
    name: nextcloud__outband

volumes:
  nextcloud_data:
    name: nextcloud__nextcloud_data

  mariadb_data:
    name: nextcloud__mariadb_data
