version: '3.8'

services:
  nextcloud:
    image: nextcloud:stable@sha256:330c866bf5aba2a000b2f4300344f5e84442ce68cd498e290d0c096271b566bc
    hostname: nextcloud
    container_name: nextcloud__nextcloud
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: mariadb
      OVERWRITEPROTOCOL: "https"

    volumes:
      - type: volume
        source: nextcloud_data
        target: /var/www/html

    deploy:
      resources:
        limits:
          memory: 1024m

    networks:
      default:
      outband:

  mariadb:
    image: mariadb:12.3.2@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
    hostname: mariadb
    container_name: nextcloud__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      default:

  nginx:
    image: nginx:1.31.1@sha256:608a100c71651bf5b773c89083b4a1ad7ef4b2bd05d7a7e552271e03123692ad
    hostname: nginx
    container_name: nextcloud__nginx
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    networks:
      default:

  cloudflared:
    image: cloudflare/cloudflared:2026.6.0-amd64@sha256:55d8bb268e90b09d3bf05a9bb5d3bc6ddad1b0b69739e4f15daaa7e6676238b6
    hostname: cloudflared
    container_name: nextcloud__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - nextcloud__cloudflared

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: nextcloud__default
    internal: true

  outband:
    name: nextcloud__outband

volumes:
  nextcloud_data:
    name: nextcloud__nextcloud_data

  mariadb_data:
    name: nextcloud__mariadb_data
