version: '3.8'

services:
  nextcloud:
    image: nextcloud:stable@sha256:5c4e09f72f096cd68379a8ae69f71e61d13da5a07430fc4a17c702a14e6a4267
    hostname: nextcloud
    container_name: nextcloud__nextcloud
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: mariadb
      OVERWRITEPROTOCOL: "https"

    volumes:
      - type: volume
        source: nextcloud_data
        target: /var/www/html

    deploy:
      resources:
        limits:
          memory: 1024m

    networks:
      default:
      outband:

  mariadb:
    image: mariadb:12.2.2@sha256:e16f61b8f6ed25111adbb1c5c19bbc2904efc8ed14029999af0cbe1c7ae18bf1
    hostname: mariadb
    container_name: nextcloud__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      default:

  nginx:
    image: nginx:1.29.6@sha256:dec7a90bd0973b076832dc56933fe876bc014929e14b4ec49923951405370112
    hostname: nginx
    container_name: nextcloud__nginx
    restart: unless-stopped

    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

    networks:
      default:

  cloudflared:
    image: cloudflare/cloudflared:2026.3.0-amd64@sha256:64f4e9d6a867f71d89ae3318460bb3c604923b4af62b1bc9e2f74ee7486e3052
    hostname: cloudflared
    container_name: nextcloud__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - nextcloud__cloudflared

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: nextcloud__default
    internal: true

  outband:
    name: nextcloud__outband

volumes:
  nextcloud_data:
    name: nextcloud__nextcloud_data

  mariadb_data:
    name: nextcloud__mariadb_data
